# Generated by Django 5.2.1 on 2025-06-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationbadge',
            name='badge_type',
            field=models.CharField(choices=[('first_donation', 'First Donation'), ('generous_donor', 'Generous Donor (RM1000+)'), ('loyal_supporter', 'Loyal Supporter (5+ donations)'), ('monthly_donor', 'Monthly Donor'), ('champion', 'Champion (RM5000+)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='donationbadge',
            unique_together={('user', 'badge_type')},
        ),
    ]
