# Generated by Django 5.1.7 on 2025-06-09 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Internal remarks by admin during verification.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_entity_details',
            field=models.TextField(default='', help_text="Details about the organization's legal status, registration numbers, etc."),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('declined', 'Declined'), ('needs_more_info', 'Needs More Information')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganisationApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='organization_application_documents/')),
                ('description', models.CharField(blank=True, help_text='Optional description of the document.', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='organizations.organization')),
            ],
        ),
    ]
