# Generated by Django 5.2.1 on 2025-06-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to='campaign_media/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
