# Generated by Django 5.2.1 on 2025-06-08 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Rename phone to phone_number
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
        # Add role field
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(
                choices=[('donor', 'Donor'), ('organization', 'Organization Main Account'), ('manager', 'Campaign Manager'), ('admin', 'Admin')],
                default='donor',
                max_length=20
            ),
        ),
        # Add location field
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        # Add created_at field
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # Add updated_at field
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
