# Generated by Django 5.1.7 on 2025-06-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_admin_remarks_and_more'),
        ('users', '0002_auto_20250608_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization this user belongs to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='organizations.organization'),
        ),
    ]
