# Generated by Django 5.1.7 on 2025-06-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='brief_description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='main_image',
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('education', 'Education'), ('health', 'Health'), ('art', 'Art'), ('environment', 'Environment'), ('community', 'Community'), ('others', 'Others')], default='others', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign/images/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
